<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Bridge : you &amp; me  | PythonBugFlow</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <meta name="generator" content="Hugo 0.75.1" />
    
    
      <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    

    
    
      <link href="/dist/css/app.d98f2eb6bcd1eaedb7edf166bd16af26.css" rel="stylesheet">
    

    

    
      
    

    

    <meta property="og:title" content="PythonBugFlow" />
<meta property="og:description" content="基础问题 1. AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;XXX&rsquo;  原因：一般情况下可能是因为拼写错误导致的改模块下确实没有对应的attribute。但还有另外一种情况是当前运行的python文件目录下有和此module模块重名的python文件，导致运行的python文件优先import了当前目录下的对应文件，所以不存在对应的attribute 解决办法：检查拼写错误或者改变文件名即可  2.   bug
File &quot;C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\lineeditor\history.py&quot;, line 82, in read_history_file for line in open(filename, &#39;r&#39;): ... UnicodeDecodeError: &#39;charmap&#39; codec can&#39;t decode byte 0x81 in position 991: character maps to &lt;undefined&gt;   原因：一般是因为打开python的history file时遇到了编码错误
  解决办法：删除位于%userprofile%/.python_history的history文件
  TensorFlow 1. TypeError: Unexpected keyword argument passed to optimizer: name Traceback (most recent call last): File &#34;visualizing_the_convnet.py&#34;, line 3, in &lt;module&gt; model = load_model(&#39;cats_and_dogs_small_2." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://horizonnn.github.io/post/pythonbugflow/" />
<meta property="article:published_time" content="2019-08-25T21:21:34+08:00" />
<meta property="article:modified_time" content="2019-08-25T21:21:34+08:00" />
<meta itemprop="name" content="PythonBugFlow">
<meta itemprop="description" content="基础问题 1. AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;XXX&rsquo;  原因：一般情况下可能是因为拼写错误导致的改模块下确实没有对应的attribute。但还有另外一种情况是当前运行的python文件目录下有和此module模块重名的python文件，导致运行的python文件优先import了当前目录下的对应文件，所以不存在对应的attribute 解决办法：检查拼写错误或者改变文件名即可  2.   bug
File &quot;C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\lineeditor\history.py&quot;, line 82, in read_history_file for line in open(filename, &#39;r&#39;): ... UnicodeDecodeError: &#39;charmap&#39; codec can&#39;t decode byte 0x81 in position 991: character maps to &lt;undefined&gt;   原因：一般是因为打开python的history file时遇到了编码错误
  解决办法：删除位于%userprofile%/.python_history的history文件
  TensorFlow 1. TypeError: Unexpected keyword argument passed to optimizer: name Traceback (most recent call last): File &#34;visualizing_the_convnet.py&#34;, line 3, in &lt;module&gt; model = load_model(&#39;cats_and_dogs_small_2.">
<meta itemprop="datePublished" content="2019-08-25T21:21:34+08:00" />
<meta itemprop="dateModified" content="2019-08-25T21:21:34+08:00" />
<meta itemprop="wordCount" content="242">



<meta itemprop="keywords" content="" />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="PythonBugFlow"/>
<meta name="twitter:description" content="基础问题 1. AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;XXX&rsquo;  原因：一般情况下可能是因为拼写错误导致的改模块下确实没有对应的attribute。但还有另外一种情况是当前运行的python文件目录下有和此module模块重名的python文件，导致运行的python文件优先import了当前目录下的对应文件，所以不存在对应的attribute 解决办法：检查拼写错误或者改变文件名即可  2.   bug
File &quot;C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\lineeditor\history.py&quot;, line 82, in read_history_file for line in open(filename, &#39;r&#39;): ... UnicodeDecodeError: &#39;charmap&#39; codec can&#39;t decode byte 0x81 in position 991: character maps to &lt;undefined&gt;   原因：一般是因为打开python的history file时遇到了编码错误
  解决办法：删除位于%userprofile%/.python_history的history文件
  TensorFlow 1. TypeError: Unexpected keyword argument passed to optimizer: name Traceback (most recent call last): File &#34;visualizing_the_convnet.py&#34;, line 3, in &lt;module&gt; model = load_model(&#39;cats_and_dogs_small_2."/>

  </head>

  <body class="ma0 avenir bg-near-white">

    
   
  

  <header>
    <div class="bg-black">
      <nav class="pv3 ph3 ph4-ns" role="navigation">
  <div class="flex-l justify-between items-center center">
    <a href="https://horizonnn.github.io/" class="f3 fw2 hover-white no-underline white-90 dib">
      Bridge : you &amp; me
    </a>
    <div class="flex-l items-center">
      

      
        <ul class="pl0 mr3">
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/post/" title="Posts page">
              Posts
            </a>
          </li>
          
        </ul>
      
      











    </div>
  </div>
</nav>

    </div>
  </header>



    <main class="pb7" role="main">
      
  
  <article class="flex-l flex-wrap justify-between mw8 center ph3">

    <header class="mt4 w-100">
      <p class="f6 b helvetica tracked">
          
        POSTS
      </p>
      <h1 class="f1 athelas mb1">PythonBugFlow</h1>
      
      <time class="f6 mv4 dib tracked" datetime="2019-08-25T21:21:34&#43;08:00">August 25, 2019</time>
      
      
    </header>

    <section class="nested-copy-line-height lh-copy serif f4 nested-links nested-img mid-gray pr4-l w-two-thirds-l"><h1 id="基础问题">基础问题</h1>
<h3 id="1-attributeerror-module-xxx-has-no-attribute-xxx">1. AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;XXX&rsquo;</h3>
<ul>
<li>原因：一般情况下可能是因为拼写错误导致的改模块下确实没有对应的attribute。但还有另外一种情况是当前运行的python文件目录下有和此module模块重名的python文件，导致运行的python文件优先import了当前目录下的对应文件，所以不存在对应的attribute</li>
<li>解决办法：检查拼写错误或者改变文件名即可</li>
</ul>
<h3 id="2">2.</h3>
<ul>
<li>
<p>bug</p>
<pre><code>File &quot;C:\ProgramData\Anaconda3\lib\site-packages\pyreadline\lineeditor\history.py&quot;, line 82, in read_history_file
    for line in open(filename, 'r'):
    ...
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 991: character maps to &lt;undefined&gt;
</code></pre></li>
<li>
<p>原因：一般是因为打开python的history file时遇到了编码错误</p>
</li>
<li>
<p>解决办法：删除位于<code>%userprofile%/.python_history</code>的history文件</p>
</li>
</ul>
<h1 id="tensorflow">TensorFlow</h1>
<h3 id="1-typeerror-unexpected-keyword-argument-passed-to-optimizer-name">1. TypeError: Unexpected keyword argument passed to optimizer: name</h3>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-shell" data-lang="shell">Traceback <span style="color:#f92672">(</span>most recent call last<span style="color:#f92672">)</span>:
  File <span style="color:#e6db74">&#34;visualizing_the_convnet.py&#34;</span>, line 3, in &lt;module&gt;
    model <span style="color:#f92672">=</span> load_model<span style="color:#f92672">(</span><span style="color:#e6db74">&#39;cats_and_dogs_small_2.h5&#39;</span><span style="color:#f92672">)</span>
  ...
TypeError: Unexpected keyword argument passed to optimizer: name
</code></pre></div><ul>
<li>
<p>原因：这部分代码加载了H5文件保存的keras Model，但是由于保存Model和加载Model的keras的版本不一致，所以会产生这个问题</p>
</li>
<li>
<p>解决办法：保持加载Model和保存Model的keras版本一致</p>
</li>
</ul>
<h3 id="2-failed-to-create-cublas-handle-cublas_status_alloc_failed">2. failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED</h3>
<ul>
<li>
<p>原因：申请GPU内存，空间不够被拒绝</p>
</li>
<li>
<p>解决办法：在代码中加入动态申请内存的显式设定</p>
</li>
</ul>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">config <span style="color:#f92672">=</span> tf<span style="color:#f92672">.</span>ConfigProto()
config<span style="color:#f92672">.</span>gpu_options<span style="color:#f92672">.</span>allow_growth <span style="color:#f92672">=</span> True
session <span style="color:#f92672">=</span> tf<span style="color:#f92672">.</span>Session(config<span style="color:#f92672">=</span>config)
</code></pre></div><h1 id="pytorch">Pytorch</h1>
<h3 id="1-runtimeerror-expected-object-of-scalar-type-double-but-got-scalar-type-float-for-argument-2-weight-in-call-to-_thnn_conv2d_forward">1. RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 &lsquo;weight&rsquo; in call to _thnn_conv2d_forward</h3>
<ul>
<li>
<p>原因：错误提示其实很明显了，就是对应对象的“weight”参数类型错误。一般来说是因为将double(float64)类型的Tensor传入了定义的网络中，而在pytorch中定义网络权重的默认类型都是float32，所以会导致这一错误</p>
</li>
<li>
<p>解决办法：将input数据和network model权重设置为统一类型即可
To convert your inputs to float (recommended):</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">inputs, labels <span style="color:#f92672">=</span> data
inputs <span style="color:#f92672">=</span> inputs<span style="color:#f92672">.</span>float()
labels <span style="color:#f92672">=</span> labels<span style="color:#f92672">.</span>float()
inputs, labels <span style="color:#f92672">=</span> Variable(inputs), Variable(labels)
</code></pre></div><p>To convert your model to double:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">model <span style="color:#f92672">=</span> Net()
model<span style="color:#f92672">.</span>double()
</code></pre></div><p>I recommend using floats instead of doubles. It’s the default tensor type in PyTorch. On GPUs, float calculations are much faster than double calculations.</p>
</li>
</ul>
<h3 id="2-the-derivative-for-target-is-not-implemented">2. the derivative for target is not implemented</h3>
<ul>
<li>
<p>原因：在定义损失函数时，作为target的参数依然存在梯度，即其requires_grad为True。这通常在训练某个神经网络子网络的是偶出现。</p>
</li>
<li>
<p>解决办法：将设置为target的参数应用一下detach函数再传入。</p>
<pre><code>target_ = target.detach()
loss = crieterion(y, target_)
</code></pre></li>
</ul>
<h1 id="numpy">numpy</h1>
<h3 id="1-valueerror-setting-an-array-element-with-sequence">1. ValueError: setting an array element with sequence</h3>
<ul>
<li>
<p>原因：numpy可以通过并行的方式加速向量间的运算，但是它要求向量中的元素应该是同一类型，若是不同类型，则进一步操作容易出现此类错误</p>
</li>
<li>
<p>解决办法：若是一定要让numpy中元素分别是不同类型的，则可以加一个object的type标识</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">x <span style="color:#f92672">=</span> np<span style="color:#f92672">.</span>array([<span style="color:#ae81ff">5</span>, [<span style="color:#ae81ff">1</span>,<span style="color:#ae81ff">2</span>,<span style="color:#ae81ff">3</span>], <span style="color:#e6db74">&#34;123&#34;</span>])
</code></pre></div></li>
</ul>
<h1 id="matplotlib">matplotlib</h1>
<h3 id="1-调用imshow显示出的图像全白">1. 调用imshow()显示出的图像全白</h3>
<ul>
<li>原因：imshow可以接受float或者int类型的参数，其有效范围分别为[0,1]和[0,255]。当参数类型为float时，imshow会默认将其裁剪到[0,1]的区间内。所以通常是输入了按照[0,255]的区间范围的float参数会出现上述问题</li>
<li>解决办法：将float参数手动转换到[0,1]区间（x = x / 255），或者将其转换为int类型（x = x.astype(&lsquo;int32&rsquo;)）。</li>
</ul>
<h3 id="2-element-is-not-attached-to-the-page-document">2. element is not attached to the page document</h3>
<ul>
<li>原因：总之就是元素在当前页面中找不到了，基本上就是元素的find语句和调用语句之间的逻辑操作导致的。</li>
<li>解决办法：获取元素与操作元素的语句之间尽量不要隔太多其他语句，最后前后相连。</li>
</ul>
<h1 id="pygame">pygame</h1>
<h3 id="1-pygamecamera-importerror-cannot-import-name-_camera">1. pygame.camera. ImportError: cannot import name &lsquo;_camera&rsquo;</h3>
<ul>
<li>原因：pygame中的camera模块默认在windows上不可用</li>
<li>解决办法：修改源代码并安装第三方依赖，详见<a href="https://github.com/pygame/pygame/issues/160">解决办法</a></li>
</ul>
<ul class="pa0">
  
</ul>
<div class="mt6">
      
      
      </div>
    </section>

    <aside class="w-30-l mt6-l">




</aside>

  </article>

    </main>
    <footer class="bg-black bottom-0 w-100 pa3" role="contentinfo">
  <div class="flex justify-between">
  <a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href="https://horizonnn.github.io/" >
    &copy; 2021 Bridge : you &amp; me
  </a>
    <div>










</div>
  </div>
</footer>

    

  <script src="/dist/js/app.3fc0f988d21662902933.js"></script>


  </body>
</html>
